version: '3.6'

services:
  mysqldb:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: eptran
        MYSQL_TCP_PORT: 3306
      ports:
        - "3306:3306"
      expose:
        - 3306
      volumes:
        - /usr/app/var/lib/mysql
      healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
  app:
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    build: .
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - mysqldb
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

